#Pull ubuntu 16.04LTS image from docker.io repo
FROM ubuntu:22.04

#Create app directory and cd into it
WORKDIR /app

#Copy the contents ONLY from host folder in the build context
COPY ./install .

#This command will be run only during docker run
#Execute the executable and print the result
CMD ["./executable"]
